# Generated by Django 5.2.7 on 2025-10-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_seed_initial_data'),
        ('listings', '0003_alter_property_category_alter_unitoption_unit_type'),
    ]

    operations = [
    ]
