# Generated by Django 5.2.7 on 2025-10-29 13:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_merge_20251024_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='property',
            name='gallery1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='gallery1'),
        ),
        migrations.AlterField(
            model_name='property',
            name='gallery2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='gallery2'),
        ),
    ]
