# Generated by Django 5.2.7 on 2025-11-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_property_cover_alter_property_gallery1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='gallery1',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='gallery2',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
