# Generated by Django 5.2.7 on 2025-11-12 13:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_property_cover_alter_property_gallery1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, choices=[('STUDIO', 'Studio Apartment'), ('RESIDENT', 'Residential'), ('1BR', '1 Bedroom Apartment'), ('2BR', '2 Bedroom Apartment'), ('3BR', '3 Bedroom Apartment'), ('4BR', '4 Bedroom Apartment'), ('FARM', 'Farm Land'), ('LAND', 'Land Asset'), ('SHOP', 'Mall Shop')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='property',
            name='gallery1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='gallery1'),
        ),
        migrations.AlterField(
            model_name='property',
            name='gallery2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='gallery2'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='unitoption',
            name='plan_0_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='unitoption',
            name='plan_3_6',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='unitoption',
            name='plan_6_12',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='unitoption',
            name='unit_type',
            field=models.CharField(choices=[('STUDIO', 'Studio Apartment'), ('RESIDENT', 'Residential'), ('1BR', '1 Bedroom Apartment'), ('2BR', '2 Bedroom Apartment'), ('3BR', '3 Bedroom Apartment'), ('4BR', '4 Bedroom Apartment'), ('FARM', 'Farm Land'), ('LAND', 'Land Asset'), ('SHOP', 'Mall Shop')], max_length=10),
        ),
    ]
