# Generated by Django 5.2.7 on 2025-11-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_property_options_alter_property_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, choices=[('STUDIO', 'Studio Apartment'), ('DUPLEX', 'Duplex'), ('RESIDENT', 'Residential'), ('1BR', '1 Bedroom Apartment'), ('2BR', '2 Bedroom Apartment'), ('3BR', '3 Bedroom Apartment'), ('4BR', '4 Bedroom Apartment'), ('5BR', '5 Bedroom Apartment'), ('FARM', 'Farm Land'), ('LAND', 'Land Asset'), ('SHOP', 'Shoping Mall')], max_length=10),
        ),
        migrations.AlterField(
            model_name='unitoption',
            name='unit_type',
            field=models.CharField(choices=[('STUDIO', 'Studio Apartment'), ('DUPLEX', 'Duplex'), ('RESIDENT', 'Residential'), ('1BR', '1 Bedroom Apartment'), ('2BR', '2 Bedroom Apartment'), ('3BR', '3 Bedroom Apartment'), ('4BR', '4 Bedroom Apartment'), ('5BR', '5 Bedroom Apartment'), ('FARM', 'Farm Land'), ('LAND', 'Land Asset'), ('SHOP', 'Shoping Mall')], max_length=10),
        ),
    ]
